language: node_js
node_js:
- node
- '7'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: 1HwG63XGK774A+njnjwS3hFeRuFHUNa/3Q3M2naA1FPhiGH15GR0QLtcSU0GkLRW1PkbiUUsHFgjAi7Izjo5v9Z9McVVCNjGIuPQ5jYUh3oDJ+bzqCpX/98hFtMP9wCyWLErLGPz0BamylxQEjsneW5CfL6Vhx+5diqa4w9AQBTr1ldrmww7fi8pnXh2pmBTG7kMgLh1EemnqQ9bFztWK3Tm6ms4t6iPdDxBb0ixoTteUYXF/PP5nNAFsi73liYrifqPPBGS5DqZSDJRBS16W7eMiD6qm+c2nkAXG2LVZZwJ7Vf1TyS13GOOjhdlPs4BmsQPe4qTb3VqJs2plAUyxtn7At12e92sUBFsYuw3ZDICiRxvL+Dn14BpO0H0WMYuxPQIhkj/uOLJYy3vOvpfUh0o4t8zqlxN7/GZRAi731jeGMiYcn4jNCe7es/sRSwyHlKjd6DIfZxBvUXwKY1Kwrqm7w1l3gUxzHJuBwk6Bil0zJ+oDXL2s7Lc/Wcp1R7Eax8YuDw/jB8AS0gbU52E0kqAXU2nEvuJ9ISP2f0UHm83U5SQR+29DMpmXDGGBATT0mjlt/pwbcCSGB4uEyi2wpHAX6afYks9C5NdgWFMXDIipa7+zm+CdtxFM2ZpuBInuCIy0LAQDyil8MboQ8tce8kl8NQH7DOcY08a5DkO49I=
  on: dist
  app: gruesome-goblin-44382
  run: npm run build
before_install:
- npm i -g npm@6.2.0
install:
- npm install
script:
- npm test
