language: node_js
node_js:
- node
- '7'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: LINhSeIQmGnm4AxrkYycXAbnLb7N9rdlLhxdI7GYSCOK/1Vt46Mv7zTO3ngOlHzhtfC6Cdm5PzDEGGOQIrn/6s47KdZzY/JArLjgTn6p3YmyEeeb5Se1ZgqVHmF8Fa6RH4AZN/c8PjhNe1NCLhazGSHtw3MKgxxp7MZudU3R3B81wzUvsMaq/IzoWqDKO7inmj0enDq5kYiPA6WMrWD+BJyKDq2BDysP4zkfpug7Yv/ZUOJdRtwJjdVg+2HWyOk6ffAOxbgneOUr2MdGUE7R+iUa7EjkNwg44u4PacXc26amRKUNStgLEVnHRUMd2Xo6YmqQIKEjC/TUVIwJuRV9n5zKHM1HS8PPRQjBIS6GXCypNnKx+SePMnVH8Op/JeoTiC++9wt4y2tNxPCkrJxpMs9n8lPdo7G3N1gIcQAhjP8iiz5LGnQKO9ASsqWTkVDFK4G+OfzXDS0INapQSt/fJNjCWUh8I7jxrgKFXO8xgoT/mYZ1WUAiFeC22YTIpyA0jQngF5yI5JMTQa1bQmgNJQCaLVWlrN3N14Kf7PysJ3FqWZ250vpkRnXxVccrVUzWvmOes0LpWr4vn8N8cNQVK6xvq5NxDUvVAr1sBZZ0asbbWLW/4j+OyVmYDBlQp8EkXYFKobu6KUcO4OwzImJbnPyk0vYEMrU0JZXgXFeWacQ=
  on: dist
  app: gruesome-goblin-44382
  run: npm run build
before_install:
- npm i -g npm@6.2.0
install:
- npm install
script:
- npm test
