language: node_js
node_js:
- node
- '7'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: tQO4hGYnr4wwd9fU0Lgh/tkzhOtchXRGz5n/G6lfLaG2mAAB1n1aQZdIQojrraonpRov64oYAtPLJOR36B2891lTo0hMTwTp7nB+f/pZw3bOFM2zdUbczpd+u975mqRKHhyeBBEmmhmitkWK/MzdJIXHw3uoH/yaXirpbhUKZ04kngfTXAzk/9+ACiBakuUBaHHaSeUhbGqFKY+lRmMI2afcgggxX+aUWX5CJba4fKPKvZnhhG4DoZ6cuMV2BG4nEmtQ5yI6Vh6GxegRlSVLSufZRw2CwbIk/MW/70KTylL6xEo/YHq3uBLBbRM18B3j450Jz/a5PVmd7girzq5gFZIxEftC+D/9AY9YtKEGjBeINYokigOdXePKMaHD5XAmIqjLDHKcmJAvU9bGwTX2XraF9lR6oYG28D9aZuACq0mEj5fvSL9NdO/60Y66Ksha3Lykr4b6gCaW4nsovhaIgYQflXjnlrUq9N0ueworui3nbtxKx6K5eAcHZLX2JxJupBKJaKmCsygc8BO5LRlIkFjMqXMYSrm3PyfABLrAkfzWXbctPLvpRzqXzg/EP85qaDpZS+QXvQGySRwlQZwNHhf2Lt3+mzXuM5n+S1CQ2Vvfs2DNm2O96uCxrfpDxJwl8ZNp+7QKY1V4Qbb4kWCcGmDnnYxBJvUgGTV23Atndl0=
  on: master
  app: gruesome-goblin-44382
before_install:
- npm i -g npm@6.2.0
install:
- npm install
script:
- npm test
