language: node_js
node_js:
- node
- '7'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key: heroku api key
  on: production
  app: gruesome-goblin-44382
before_install:
- npm i -g npm@6.2.0
install:
- npm install
script:
- npm test
env:
  global:
    secure: VJPtRTu6gTzXiDsr2eqrTisjrppCksvsalqDsTduIR1tMid8zT2rZk3XIsBRsrhwc51pEpK3xY/V4Ep58nUC6j06IdDJQAwSdZhrR3IW3Ne3DHJtqIgv5XyJ7EgI3WtBviiozpf9na+vq//NeBI3LVFXFjCqewbMUu3I3+fSrWfolJKsBHpfrONkdtfrT/t1DaWsYF6falp4Vc7wYROAUreYL1uTDZgoPsMIuL0aUHAOAIvcDSOcwOYNsZeitcnKOl9VVSMan1FsqoA8NmHfoOl7d0ytNoxPiJIAA0nuEAh2hcLxspcveNf2+jp1IwkTey5McEsOcCNDc+iKY8jgUJUFIlQDuTUCap1Pm48hg0zmBMCIIz1Lb0swe9DghWUPxqOmtr7yhImvLUXqvcRjGs1MAUWmW+uXuyfQgxYHAYHE3vhiCzSs+karehWatUsfyoUz1dxsWWZCBOJcZIcHkkUidi6vU+yOh0oR5tqJ7jk2GtINOkr9Q+NVR9GFpx6KHVrZ9/L1KY4orkGTwdIerBSjNje/RWasF7rwWE1RW9LQzmWpzY6lSC0k0iT2dEb67Yb4Ta91Y6EqWIHNjxJBjtW0MAfouaVHA8DTsb+4ccL8MuNtODKyd2sG4pNw+jbveS0DhnQSeIGzLW8+yI2S9dIfnyQf1tZMysceyE1LU9U=
