language: node_js
node_js:
- node
- '7'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: mkvusdbkdrtSdDS6ucfHp8JDVueAwWPgtT/AxcgEiPBZPXnavsEudIyJlSZWYF80801wm9b+lX2n/SYr0gYOgU1uQQCDaa4Bj/RNOE6Ac+Qmy8y2L9xLGAf+mZBvpSDkg+YWsZRpBTRVxCJwPVN4n5XNwRi6i55g066sEK3YJBfVtsdkAR48oUY7XBMHwUjiLxcfuc/KdrmnUuHPvEPqXjAKoV2YJhtAJnxPN025apHMooi8Rd9vPX2WAqw1LNshH//L1xjci4KGYbbagFAtLJvXfeH1FpX3DXq+HpzhvuNxt5o8GmZKoAnQrmWsFO1LkaRGfG+XfxLDK4xywh2VFjuNzetTAalkBGbuLs19gwN7SXAMOWcIv0MY/NJw14X5VYRQMr1qnjV9U9IJXdH4t5WOWCajoWDeYL0P2EGX2o/BIaRx+L58QLsFbbSn5vfSfItZ8e8IdaXK/Fp7lzqMwovZdZI11x4vXBrD4OE9GNAj2AQlr5o4Ksd9JdYktZ3u+M96KqfRzKA08dWTQ659lpSlpsn0cBV5MmejW7s0sSNxudFi3TJ9bsfZLXQ1OH0xcf2jJuuWpW3SNNQAcPZ+uc4GPOG677m6PYOlAB0QdVgKmJwnp1iCikLooBXAybbmZXTTEfZOY6dFFNrahW1+WobLCdeFaQnbviUYnO+FDLk=
  on: dist
  app: gruesome-goblin-44382
before_install:
- npm i -g npm@6.2.0
install:
- npm install
script:
- npm test
