language: node_js
node_js:
- node
- '7'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key: HEROKU_API_KEY
  on: dist
  app: gruesome-goblin-44382
  run: npm run build
before_install:
- npm i -g npm@6.2.0
install:
- npm install
script:
- npm test
