language: node_js
node_js:
- node
- '7'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: jUtR52WLRaQCcQtzqlHiN0yhqJRNbEskVNXMmp18YRtAgM8Md1GK9uGgGCOXA7127b1bmlfyG4v8fvehWgO1xaV3RbA/JgEtURlSYdvpd0cmJDucHVU5AwSHtPf8PJnJynPul6xRbzdEUF9C7CbpiiUQ7knvgoINi2GUnALs6ZEtnbtVqqqJZj/k0r7yNvEmaW0abFvc/9Hvhy0HNsKggWO9gIqqghce46tOPi5D7es5APQNxGKjTzxJge1JGmxQtCdRruwrlGYwypwVF5wuYZd89zvSa4i17o7kOs8OydCvedC0tTBTWwwqOJbnsxkvtPq2MnFZrTRM40yv1vIvZKDuMRm2jGQuZ0Fh0tqoKnUHt2B+H95COusGjM6P7UvK6eJyrVaNXFD79Cu1wDMjpbUxlvbl3xNUbq2hu7tBoZ+s8P24n8UfMpfC17uXobncE9Fdafng5N6Z1Fz7b+OOwbifBV2TgL9t3UOZtV2Ffig7syPIPAbM+S14BQt2jGTL+lg+ah7HuYUJ35ZUo92nv8+nlwFK/nyvK+cNTIjU+1n0WTmGHUBfm7kojvq27nU1OC5vDcEJIl4zi+Sn9e54uayn85pW/muD+9cMrG99fKsemHh3qgEY/zqDGWksRQmynODS+DrmgqY1W/kHnE1cGbX+8LDYYi/dXbrHisjIo7c=
  on: master
  app: gruesome-goblin-44382
before_install:
- npm i -g npm@6.2.0
install:
- npm install
script:
- npm test
